# Generated by Django 5.0.14 on 2025-10-17 00:26

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkateSpot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1000)),
                (
                    "spot_type",
                    models.CharField(
                        choices=[
                            ("street", "Street"),
                            ("park", "Park"),
                            ("skatepark", "Skatepark"),
                            ("bowl", "Bowl"),
                            ("vert", "Vert"),
                            ("mini_ramp", "Mini Ramp"),
                            ("stairs", "Stairs"),
                            ("rail", "Rail"),
                            ("ledge", "Ledge"),
                            ("gap", "Gap"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("is_public", models.BooleanField(default=True)),
                ("requires_permission", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skate_spots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "skate spot",
                "verbose_name_plural": "skate spots",
                "db_table": "skate_spots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner"], name="skate_spots_user_id_6b147c_idx"
                    ),
                    models.Index(fields=["city"], name="skate_spots_city_9e18b0_idx"),
                    models.Index(
                        fields=["country"], name="skate_spots_country_240519_idx"
                    ),
                    models.Index(
                        fields=["spot_type"], name="skate_spots_spot_ty_272b04_idx"
                    ),
                    models.Index(
                        fields=["difficulty"], name="skate_spots_difficu_2c3f51_idx"
                    ),
                ],
            },
        ),
    ]
